### ISSUE TITLE
Application Tier 1?

### ISSUE THREAD

**Issue by Mbnl1197** [MarcoHannemann/fluxnetcdf#2]
Hi, is this code applicable to Fluxnet2015 Tier1?

Thanks!

**Comment by MarcoHannemann** [comment]
Yes! Tier 1 is a smaller subset of the FLUXNET2015 dataset. Tier 2 includes sites with a stricter data policy. Format-wise they should not differ. You can read more about this [here](https://fluxnet.org/data/fluxnet2015-dataset/) under the section **Data Policies**.
